### ISSUE TITLE
Repositories, naming and structure

### ISSUE THREAD

**Issue by zdne** [rwmbook/registry-docs#3]
I find the current structure and naming of DISCO repositories confusing. Would it 

e.g.:

https://github.com/rwmbook/registry
https://github.com/mamund/2018-02-sacon-workshop/tree/master/examples

Would it make sense to crate a DISCO org on GitHub and move the spec and examples there?

**Comment by mamund** [comment]
yep -- this started as as super MVP project for a single talk and has grown into something more.

i have created an org here: https://github.com/open-disco and added you as a member.
